"""fix_user_and_fk

Revision ID: aea107d08746
Revises: 0556ceee4fa6
Create Date: 2026-02-17 13:28:38.518131

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'aea107d08746'
down_revision: Union[str, Sequence[str], None] = '0556ceee4fa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    nofallbackstrategy = sa.Enum('ANY', name='nofallbackstrategy')
    nofallbackstrategy.create(op.get_bind())

    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN strategy TYPE nofallbackstrategy 
        USING strategy::nofallbackstrategy
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        ALTER TABLE users 
        ALTER COLUMN strategy TYPE VARCHAR(255) 
        USING strategy::varchar
    """)

    sa.Enum(name='nofallbackstrategy').drop(op.get_bind())
    # ### end Alembic commands ###
