"""fix_reviews_duplicate

Revision ID: fc41e0d1f7b9
Revises: f9ca23963e00
Create Date: 2026-02-19 00:10:04.789195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc41e0d1f7b9'
down_revision: Union[str, Sequence[str], None] = 'f9ca23963e00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_experiment_id_approvedBy', 'reviews', ['experiment_id', 'approvedBy'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_experiment_id_approvedBy', 'reviews', type_='unique')
    # ### end Alembic commands ###
