"""fix_nofallbackstrategy

Revision ID: 37a4cfa26344
Revises: 7924286e965e
Create Date: 2026-02-18 18:23:11.381368

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '37a4cfa26344'
down_revision: Union[str, Sequence[str], None] = '7924286e965e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE nofallbackstrategy ADD VALUE 'ZERO';")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
