"""fix_flags

Revision ID: e15a5f8fbaaf
Revises: 4ff79841ad0e
Create Date: 2026-02-20 13:32:22.068835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e15a5f8fbaaf'
down_revision: Union[str, Sequence[str], None] = '4ff79841ad0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'enabled')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
