"""fix_approver_safe_delete

Revision ID: 77e442ddc513
Revises: 37a4cfa26344
Create Date: 2026-02-18 22:01:34.204775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77e442ddc513'
down_revision: Union[str, Sequence[str], None] = '37a4cfa26344'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvers', sa.Column('isActive', sa.Boolean(), nullable=False))
    op.create_unique_constraint('uq_experimenter_id_approver_id', 'approvers', ['experimenter_id', 'approver_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_experimenter_id_approver_id', 'approvers', type_='unique')
    op.drop_column('approvers', 'isActive')
    # ### end Alembic commands ###
