"""fix_createdby_event_catalog

Revision ID: 20d552f2d4f7
Revises: 62b51ad442bf
Create Date: 2026-02-22 13:15:25.504751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20d552f2d4f7'
down_revision: Union[str, Sequence[str], None] = '62b51ad442bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_catalog', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event_catalog', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
