"""fix_many2many2many2one

Revision ID: 96ab0959bf57
Revises: 9cb212455a67
Create Date: 2026-02-19 22:58:09.537086

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '96ab0959bf57'
down_revision: Union[str, Sequence[str], None] = '9cb212455a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_catalog_metric_catalog')
    op.add_column('event_catalog', sa.Column('metricCatalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.create_foreign_key("fk_event_catalog_metric_catalog", 'event_catalog', 'metric_catalog', ['metricCatalog_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_event_catalog_metric_catalog", 'event_catalog', type_='foreignkey')
    op.drop_column('event_catalog', 'metricCatalog_code')
    op.create_table('event_catalog_metric_catalog',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('event_catalog_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metric_catalog_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_catalog_code'], ['event_catalog.code'], name=op.f('event_catalog_metric_catalog_event_catalog_code_fkey')),
    sa.ForeignKeyConstraint(['metric_catalog_code'], ['metric_catalog.code'], name=op.f('event_catalog_metric_catalog_metric_catalog_code_fkey')),
    sa.PrimaryKeyConstraint('id', 'event_catalog_code', 'metric_catalog_code', name=op.f('event_catalog_metric_catalog_pkey'))
    )
    # ### end Alembic commands ###
