"""drop_table_review_history

Revision ID: 7924286e965e
Revises: e4f04e25945e
Create Date: 2026-02-18 17:51:52.838524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7924286e965e'
down_revision: Union[str, Sequence[str], None] = 'e4f04e25945e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews_results_history')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews_results_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('approved', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rejected', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('deleted', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('createdAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('reviews_results_history_pkey'))
    )
    # ### end Alembic commands ###
