"""fix_approvers_duplicate

Revision ID: f9ca23963e00
Revises: e2715f4afc93
Create Date: 2026-02-18 23:12:47.120594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ca23963e00'
down_revision: Union[str, Sequence[str], None] = 'e2715f4afc93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_experimenter_id_approver_id'), 'approvers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_experimenter_id_approver_id'), 'approvers', ['experimenter_id', 'approver_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
