"""fix_approver_createdby

Revision ID: e2715f4afc93
Revises: 77e442ddc513
Create Date: 2026-02-18 22:49:44.770961

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e2715f4afc93'
down_revision: Union[str, Sequence[str], None] = '77e442ddc513'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvers', sa.Column('addedBy', sa.Uuid(), nullable=False))
    op.create_foreign_key("fk_approver_addedby", 'approvers', 'users', ['addedBy'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_approver_addedby", 'approvers', type_='foreignkey')
    op.drop_column('approvers', 'addedBy')
    # ### end Alembic commands ###
