"""add_reviews

Revision ID: 0556ceee4fa6
Revises: 98f9c5c04858
Create Date: 2026-02-17 13:10:36.718007

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0556ceee4fa6'
down_revision: Union[str, Sequence[str], None] = '98f9c5c04858'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviews_results_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('approved', sa.Integer(), nullable=False),
    sa.Column('rejected', sa.Integer(), nullable=False),
    sa.Column('deleted', sa.Integer(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('approvers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experimenter_id', sa.Uuid(), nullable=False),
    sa.Column('approver_id', sa.Uuid(), nullable=False),
    sa.Column('addedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experimenter_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('result', sa.Enum('APPROVED', 'IMPROVEMENT', 'REJECTED', name='reviewresult'), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('approvedBy', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['approvedBy'], ['approvers.id'], ),
    sa.ForeignKeyConstraint(['experiment_code'], ['experiments.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('approvers')
    op.drop_table('reviews_results_history')
    # ### end Alembic commands ###
