"""fix_metric_fields

Revision ID: 4ff79841ad0e
Revises: ed12444aa6d1
Create Date: 2026-02-20 12:29:07.831928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4ff79841ad0e'
down_revision: Union[str, Sequence[str], None] = 'ed12444aa6d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('workedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('metric_history')
    op.drop_column('metrics', 'time_from')
    op.drop_column('metrics', 'time_to')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('time_to', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('metrics', sa.Column('time_from', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_table('metric_history',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('metric_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('history', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('workedAt', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], name=op.f('metric_history_metric_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('metric_history_pkey'))
    )
    op.drop_table('guardrail_history')
    # ### end Alembic commands ###
