"""fix_metric_catalog_event_catalog_relationship2many2many_again

Revision ID: b46a92cbea42
Revises: e15a5f8fbaaf
Create Date: 2026-02-20 16:29:32.562421

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b46a92cbea42'
down_revision: Union[str, Sequence[str], None] = 'e15a5f8fbaaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_metric_links',
    sa.Column('event_catalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_catalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('value_field', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.ForeignKeyConstraint(['event_catalog_code'], ['event_catalog.code'], ),
    sa.ForeignKeyConstraint(['metric_catalog_code'], ['metric_catalog.code'], ),
    sa.PrimaryKeyConstraint('event_catalog_code', 'metric_catalog_code')
    )
    op.drop_constraint(op.f('fk_event_catalog_metric_catalog'), 'event_catalog', type_='foreignkey')
    op.drop_column('event_catalog', 'metricCatalog_code')
    op.drop_column('metric_catalog', 'calculationConfig')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metric_catalog', sa.Column('calculationConfig', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('event_catalog', sa.Column('metricCatalog_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_event_catalog_metric_catalog'), 'event_catalog', 'metric_catalog', ['metricCatalog_code'], ['code'])
    op.drop_table('event_metric_links')
    # ### end Alembic commands ###
