"""main_structure

Revision ID: be9cbcd81bee
Revises: b4506e2b7d8a
Create Date: 2026-02-16 19:13:13.756361

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'be9cbcd81bee'
down_revision: Union[str, Sequence[str], None] = 'b4506e2b7d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False))
    op.add_column('flags', sa.Column('createdBy', sa.Uuid(), nullable=False))
    op.drop_constraint(op.f('flags_key_key'), 'flags', type_='unique')
    op.drop_index(op.f('ix_flags_id'), table_name='flags')
    op.create_index(op.f('ix_flags_code'), 'flags', ['code'], unique=True)
    op.create_unique_constraint(None, 'flags', ['id'])
    op.create_foreign_key(None, 'flags', 'users', ['createdBy'], ['id'])
    op.drop_column('flags', 'key')

    op.add_column('users', sa.Column('required', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('useFallback', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('strategy', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True))

    op.create_table('guardrail_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_guardrail_actions_code'), 'guardrail_actions', ['code'], unique=True)
    op.create_table('metric_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('isSystem', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('calculationConfig', sa.JSON(), nullable=True),
    sa.Column('createdBy', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_metric_catalog_code'), 'metric_catalog', ['code'], unique=True)
    op.create_table('event_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('metricCatalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('requiredParams', sa.JSON(), nullable=True),
    sa.Column('requiresExposure', sa.Boolean(), nullable=False),
    sa.Column('isSystem', sa.Boolean(), nullable=False),
    sa.Column('inArchive', sa.Boolean(), nullable=False),
    sa.Column('createdBy', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['metricCatalog_code'], ['metric_catalog.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_event_catalog_code'), 'event_catalog', ['code'], unique=True)
    op.create_table('experiments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('flag_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'IN_REVIEW', 'APPROVED', 'RUNNING', 'PAUSED', 'COMPLETED', 'ARCHIVED', 'REJECTED', name='experimentstatus'), nullable=False),
    sa.Column('version', sa.Float(), nullable=False),
    sa.Column('part', sa.Integer(), nullable=False),
    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('isCurrent', sa.Boolean(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('createdBy', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['createdBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flag_code'], ['flags.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_experiments_code'), 'experiments', ['code'], unique=True)
    op.create_table('metrics',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_id', sa.Uuid(), nullable=False),
    sa.Column('metricCatalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('time_from', sa.DateTime(), nullable=True),
    sa.Column('time_to', sa.DateTime(), nullable=True),
    sa.Column('window', sa.Integer(), nullable=True),
    sa.Column('threshold', sa.Integer(), nullable=True),
    sa.Column('action_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('addedBy', sa.Uuid(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['action_code'], ['guardrail_actions.code'], ),
    sa.ForeignKeyConstraint(['addedBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.ForeignKeyConstraint(['metricCatalog_code'], ['metric_catalog.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('variants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('experiment_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('isControl', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['experiment_code'], ['experiments.code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=True)
    op.create_table('decisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('variant_id', sa.Uuid(), nullable=False),
    sa.Column('isRequested', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=True)
    op.create_table('metric_history',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metric_id', sa.Uuid(), nullable=False),
    sa.Column('history', sa.JSON(), nullable=True),
    sa.Column('workedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['metric_id'], ['metrics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('eventKey', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('decision_id', sa.Uuid(), nullable=False),
    sa.Column('eventCatalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], ),
    sa.ForeignKeyConstraint(['eventCatalog_code'], ['event_catalog.code'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eventKey'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'strategy')
    op.drop_column('users', 'useFallback')
    op.drop_column('users', 'required')
    op.add_column('flags', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'flags', type_='foreignkey')
    op.drop_constraint(None, 'flags', type_='unique')
    op.drop_index(op.f('ix_flags_code'), table_name='flags')
    op.create_index(op.f('ix_flags_id'), 'flags', ['id'], unique=False)
    op.create_unique_constraint(op.f('flags_key_key'), 'flags', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_column('flags', 'createdBy')
    op.drop_column('flags', 'code')
    op.drop_table('events')
    op.drop_table('metric_history')
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_table('metrics')
    op.drop_index(op.f('ix_experiments_code'), table_name='experiments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_event_catalog_code'), table_name='event_catalog')
    op.drop_table('event_catalog')
    op.drop_index(op.f('ix_metric_catalog_code'), table_name='metric_catalog')
    op.drop_table('metric_catalog')
    op.drop_index(op.f('ix_guardrail_actions_code'), table_name='guardrail_actions')
    op.drop_table('guardrail_actions')
    # ### end Alembic commands ###
