"""fix_datetime

Revision ID: b3656c6ac3b8
Revises: 0bd72cf7b647
Create Date: 2026-02-13 00:30:25.270737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3656c6ac3b8'
down_revision: Union[str, Sequence[str], None] = '0bd72cf7b647'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('flags', sa.Column('updatedAt', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('flags', 'updatedAt')
    # ### end Alembic commands ###
