"""fix_event_metric_links_fields

Revision ID: 1ac43564a07d
Revises: b46a92cbea42
Create Date: 2026-02-20 17:03:36.058347

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '1ac43564a07d'
down_revision: Union[str, Sequence[str], None] = 'b46a92cbea42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_metric_links', sa.Column('eventCatalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('event_metric_links', sa.Column('metricCatalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_constraint(op.f('event_metric_links_event_catalog_code_fkey'), 'event_metric_links', type_='foreignkey')
    op.drop_constraint(op.f('event_metric_links_metric_catalog_code_fkey'), 'event_metric_links', type_='foreignkey')
    op.drop_column('event_metric_links', 'metric_catalog_code')
    op.drop_column('event_metric_links', 'event_catalog_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_metric_links', sa.Column('event_catalog_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('event_metric_links', sa.Column('metric_catalog_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('event_metric_links_metric_catalog_code_fkey'), 'event_metric_links', 'metric_catalog', ['metric_catalog_code'], ['code'])
    op.create_foreign_key(op.f('event_metric_links_event_catalog_code_fkey'), 'event_metric_links', 'event_catalog', ['event_catalog_code'], ['code'])
    op.drop_column('event_metric_links', 'metricCatalog_code')
    op.drop_column('event_metric_links', 'eventCatalog_code')
    # ### end Alembic commands ###
