"""fix_event_catalog_metric_catalog_relationship

Revision ID: 4fdcd464b9f1
Revises: 509ee47eadb8
Create Date: 2026-02-19 19:19:45.844516

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '4fdcd464b9f1'
down_revision: Union[str, Sequence[str], None] = '509ee47eadb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_catalog_metric_catalog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_catalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metric_catalog_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['event_catalog_code'], ['event_catalog.code'], ),
    sa.ForeignKeyConstraint(['metric_catalog_code'], ['metric_catalog.code'], ),
    sa.PrimaryKeyConstraint('id', 'event_catalog_code', 'metric_catalog_code')
    )
    op.drop_constraint(op.f('event_catalog_metricCatalog_code_fkey'), 'event_catalog', type_='foreignkey')
    op.drop_column('event_catalog', 'metricCatalog_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_catalog', sa.Column('metricCatalog_code', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('event_catalog_metricCatalog_code_fkey'), 'event_catalog', 'metric_catalog', ['metricCatalog_code'], ['code'])
    op.drop_table('event_catalog_metric_catalog')
    # ### end Alembic commands ###
