"""fix_guardrail_actions

Revision ID: 77072535b053
Revises: 96ab0959bf57
Create Date: 2026-02-19 23:12:08.968036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77072535b053'
down_revision: Union[str, Sequence[str], None] = '96ab0959bf57'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('metrics_action_code_fkey'), 'metrics', type_='foreignkey')
    op.drop_column('metrics', 'action_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics', sa.Column('action_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('metrics_action_code_fkey'), 'metrics', 'guardrail_actions', ['action_code'], ['code'])
    # ### end Alembic commands ###
