"""fix_event_metric_links_fields2

Revision ID: 9bb4e22d77c2
Revises: 1ac43564a07d
Create Date: 2026-02-20 17:10:44.783732

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9bb4e22d77c2'
down_revision: Union[str, Sequence[str], None] = '1ac43564a07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_metric_links', sa.Column('id', sa.Uuid(), nullable=False))
    op.create_foreign_key("fk_metric_catalog", 'event_metric_links', 'metric_catalog', ['metricCatalog_code'], ['code'])
    op.create_foreign_key("fk_event_catalog", 'event_metric_links', 'event_catalog', ['eventCatalog_code'], ['code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_metric_catalog", 'event_metric_links', type_='foreignkey')
    op.drop_constraint("fk_event_catalog", 'event_metric_links', type_='foreignkey')
    op.drop_column('event_metric_links', 'id')
    # ### end Alembic commands ###
