"""fix_guardrail_actions

Revision ID: aa7318a64fbf
Revises: 77072535b053
Create Date: 2026-02-19 23:12:33.954178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa7318a64fbf'
down_revision: Union[str, Sequence[str], None] = '77072535b053'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guardrail_actions_code'), table_name='guardrail_actions')
    op.drop_table('guardrail_actions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('guardrail_actions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guardrail_actions_pkey'))
    )
    op.create_index(op.f('ix_guardrail_actions_code'), 'guardrail_actions', ['code'], unique=True)
    # ### end Alembic commands ###
