"""fix_metric_catalog_nullable_fields

Revision ID: 65844e79a71f
Revises: 7d6c6c45c2e4
Create Date: 2026-02-17 15:10:55.548865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65844e79a71f'
down_revision: Union[str, Sequence[str], None] = '7d6c6c45c2e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=False)
    op.drop_constraint(op.f('flags_id_key'), 'flags', type_='unique')
    op.alter_column('metric_catalog', 'createdBy',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_id'), table_name='variants')
    op.create_index(op.f('ix_variants_id'), 'variants', ['id'], unique=True)
    op.alter_column('metric_catalog', 'createdBy',
               existing_type=sa.UUID(),
               nullable=False)
    op.create_unique_constraint(op.f('flags_id_key'), 'flags', ['id'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_decisions_id'), table_name='decisions')
    op.create_index(op.f('ix_decisions_id'), 'decisions', ['id'], unique=True)
    # ### end Alembic commands ###
